// Shared style definitions for all Home page sections.
// Kept in one file since every section receives the same `styles` object as a prop.

export const getStyles = (isMobile) => ({
  page: { fontFamily: "system-ui, -apple-system, sans-serif", color: "#24211f", overflowX: "hidden" },

  hero: {
    position: "relative",
    minHeight: isMobile ? "480px" : "600px",
    display: "flex",
    alignItems: "center",
    overflow: "hidden",
  },
  heroVideoBg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },

  muteBtn: {
    position: "absolute",
    bottom: "24px",
    right: "24px",
    zIndex: 3,
    width: "42px",
    height: "42px",
    borderRadius: "50%",
    background: "rgba(0, 0, 0, 0.45)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    color: "#fff",
    fontSize: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  heroTextScrim: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(90deg, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.35) 40%, rgba(0,0,0,0) 70%)",
    zIndex: 1,
  },

  heroInner: {
    position: "relative",
    zIndex: 2,
    width: "100%",
    padding: isMobile ? "48px 20px 64px" : "0 56px",
  },
  heroText: { maxWidth: "620px" },
  heroTag: {
    display: "inline-flex",
    alignItems: "center",
    background: "rgba(255, 255, 255, 0.12)",
    color: "#ffffff",
    fontSize: "12.5px",
    fontWeight: 600,
    padding: "7px 16px",
    borderRadius: "30px",
    marginBottom: "22px",
    letterSpacing: "0.03em",
  },
  badgePulse: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#22c55e",
    marginRight: "10px",
    display: "inline-block",
    animation: "pulseGlow 2s infinite ease-in-out",
  },
  heroHeading: {
    fontSize: isMobile ? "34px" : "54px",
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1.14,
    margin: "0 0 20px",
    letterSpacing: "-0.01em",
    textShadow: "0 4px 20px rgba(0,0,0,0.25)",
  },
  heroAccentWrap: {
    position: "relative",
    display: "inline-block",
  },
  squiggleSvg: {
    position: "absolute",
    left: 0,
    bottom: isMobile ? "-8px" : "-12px",
    width: "100%",
    height: isMobile ? "12px" : "16px",
  },
  heroSub: {
    color: "#FCEBEB",
    fontSize: isMobile ? "14px" : "16px",
    lineHeight: 1.6,
    maxWidth: "460px",
    margin: "0 0 32px",
    textShadow: "0 1px 6px rgba(0,0,0,0.2)",
  },
  heroActions: { display: "flex", gap: "14px", flexWrap: "wrap", alignItems: "center" },
  btnPrimary: {
    color: "#A21212",
    textDecoration: "none",
    padding: "14px 28px",
    borderRadius: "30px",
    fontSize: "14.5px",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
  },
  btnOutline: {
    background: "transparent",
    color: "#fff",
    textDecoration: "none",
    padding: "13px 28px",
    borderRadius: "30px",
    fontSize: "14.5px",
    fontWeight: 700,
    border: "1.5px solid rgba(255, 255, 255, 0.45)",
  },

  floatCardGlass: {
    marginTop: "40px",
    display: "inline-flex",
    background: "rgba(255, 255, 255, 0.88)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: "18px",
    padding: "16px 28px",
    boxShadow: "0 20px 40px rgba(0, 0, 0, 0.22)",
    border: "1px solid rgba(255, 255, 255, 0.6)",
    alignItems: "center",
    gap: "24px",
  },
  floatStat: { textAlign: "center" },
  floatValue: {
    fontSize: "22px",
    fontWeight: 800,
    color: "#C41E1E",
    letterSpacing: "-0.02em"
  },
  floatLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#4a433e",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginTop: "2px"
  },
  floatDivider: { width: "1px", height: "32px", background: "rgba(0,0,0,0.08)" },

  wave: {
    position: "absolute",
    bottom: "-2px",
    left: 0,
    width: "100%",
    height: isMobile ? "30px" : "50px",
    display: "block",
    zIndex: 2,
  },

  videoSection: {
    padding: isMobile ? "56px 20px" : "90px 48px",
    position: "relative",
    overflow: "hidden", // Keeps falling cards contained cleanly inside the section
    backgroundColor: "#FFFFFF",
    /* Removed grid lines. Soft Pink glow (Left) & Warm Yellow glow (Right) */
    backgroundImage: `
      radial-gradient(circle at 0% 35%, rgba(244, 114, 182, 0.2) 0%, transparent 45%),
      radial-gradient(circle at 100% 20%, rgba(253, 224, 71, 0.25) 0%, transparent 45%)
    `,
    backgroundSize: "100% 100%",
  },
  videoSectionInner: {
    maxWidth: "900px",
    margin: "0 auto",
    textAlign: "center",
  },
  videoWrapper: {
    position: "relative",
    width: "100%",
    paddingTop: "56.25%",
    borderRadius: "18px",
    overflow: "hidden",
    marginTop: "24px",
    background: "#000",
    border: "6px solid rgba(255,255,255,0.9)",
    transform: "perspective(1200px) rotateX(3deg)",
    transformStyle: "preserve-3d",
    boxShadow:
      "0 30px 60px rgba(0,0,0,0.45), 0 15px 25px rgba(0,0,0,0.3), inset 0 0 0 1px rgba(255,255,255,0.1)",
    transition: "transform 0.4s ease, box-shadow 0.4s ease",
  },

  aboutSection: {
    display: "flex",
    flexDirection: isMobile ? "column" : "row",
    alignItems: "center",
    gap: isMobile ? "36px" : "60px",
    padding: isMobile ? "48px 20px" : "80px 56px",
    /* Darker rich crimson spotlight in top-left corner fading smoothly to clean white */
    background: "radial-gradient(circle at 0% 0%, rgba(196, 30, 30, 0.18) 0%, rgba(196, 30, 30, 0.05) 35%, #FFFFFF 70%)",
    position: "relative",
    /* Removed borderTop & borderBottom lines */
  },
  aboutText: { flex: 1.1 },

  eyebrow: {
    fontSize: "12px",
    letterSpacing: "0.15em",
    color: "#C41E1E",
    textTransform: "uppercase",
    fontWeight: 800,
    marginBottom: "12px",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    background: "#FEF2F2",
    padding: "5px 14px",
    borderRadius: "20px",
    border: "1px solid #FEE2E2",
  },
  eyebrowDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    background: "#C41E1E",
    display: "inline-block",
  },
  aboutHeading: {
    fontSize: isMobile ? "28px" : "38px",
    color: "#1a1615",
    marginBottom: "20px",
    lineHeight: 1.2,
    fontWeight: 800,
    letterSpacing: "-0.02em",
  },
  headingAccent: {
    color: "#C41E1E",
  },
  paragraphLeft: {
    fontSize: isMobile ? "14.5px" : "15.5px",
    lineHeight: 1.7,
    color: "#4a433e",
    marginBottom: "20px",
  },

  /* Feature Pills */
  aboutPillsGrid: {
    display: "grid",
    gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr",
    gap: "14px",
    marginBottom: "24px",
  },
  aboutPill: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    background: "#ffffff",
    padding: "12px 16px",
    borderRadius: "14px",
    border: "1px solid #FEE2E2",
    boxShadow: "0 4px 15px rgba(196, 30, 30, 0.04)",
  },
  aboutPillIcon: {
    fontSize: "20px",
    background: "#FEF2F2",
    width: "38px",
    height: "38px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  aboutPillTitle: {
    fontSize: "13.5px",
    fontWeight: 700,
    color: "#1a1615",
  },
  aboutPillSub: {
    fontSize: "11.5px",
    color: "#786f68",
  },

  /* CTA Link */
  aboutCta: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: "#C41E1E",
    fontSize: "15px",
    fontWeight: 800,
    textDecoration: "none",
    marginTop: "8px",
  },
  aboutCtaArrow: {
    fontSize: "18px",
    transition: "transform 0.2s ease",
  },

  /* Right Image Card & Glass Badge */
  aboutImageWrap: {
    flex: 0.9,
    width: "100%",
  },
  aboutImageCard: {
    position: "relative",
    borderRadius: "24px",
    overflow: "hidden",
    boxShadow: "0 16px 40px rgba(196, 30, 30, 0.1)",
    border: "4px solid #ffffff",
    height: isMobile ? "280px" : "400px",
  },
  aboutImage: {
    width: "100%",
    height: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "#f1e5e5",
  },
  aboutImageOverlay: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(180deg, rgba(0,0,0,0) 60%, rgba(142,22,22,0.4) 100%)",
  },
  aboutGlassBadge: {
    position: "absolute",
    bottom: "20px",
    left: "20px",
    background: "rgba(255, 255, 255, 0.92)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: "16px",
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    gap: "14px",
    boxShadow: "0 10px 25px rgba(0, 0, 0, 0.15)",
    border: "1px solid rgba(255, 255, 255, 0.8)",
  },
  badgeNumber: {
    fontSize: "24px",
    fontWeight: 900,
    color: "#C41E1E",
    lineHeight: 1,
  },
  badgeText: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#2D0B0E",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    maxWidth: "110px",
    lineHeight: 1.25,
  },

  section: { padding: isMobile ? "40px 20px" : "72px 56px", background: "#ffffff" },
  sectionShaded: { background: "#FEF2F2" },
  sectionInner: { maxWidth: "1200px", margin: "0 auto" },
  sectionHeaderLeft: { marginBottom: "36px", maxWidth: "600px" },
  sectionHeadingLeft: { fontSize: isMobile ? "24px" : "32px", color: "#1a1615", marginBottom: "10px", fontWeight: 800, letterSpacing: "-0.01em" },
  sectionSubLeft: { color: "#6b625a", fontSize: isMobile ? "14px" : "15px", lineHeight: 1.6 },

  grid3: {
    display: "grid",
    gridTemplateColumns: isMobile ? "1fr" : "repeat(3, 1fr)",
    gap: isMobile ? "18px" : "28px",
  },

  reasonCard: {
    background: "#ffffff",
    borderRadius: "22px",
    overflow: "hidden",
    textAlign: "left",
    border: "1px solid #FEE2E2",
    boxShadow: "0 8px 25px rgba(196, 30, 30, 0.06)",
    display: "flex",
    flexDirection: "column",
  },
  reasonCardBody: {
    padding: "24px 22px 28px",
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },

  iconCircle: {
    width: "100%",
    height: isMobile ? "180px" : "210px",
    overflow: "hidden",
    position: "relative",
  },

  reasonImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  cardTitle: {
    fontSize: "20px",
    color: "#1a1615",
    marginBottom: "10px",
    fontWeight: 800,
    letterSpacing: "-0.01em"
  },
  cardText: {
    fontSize: "14.5px",
    color: "#5c544e",
    lineHeight: 1.65
  },

  courseCard: {
    background: "#ffffff",
    borderRadius: "20px",
    overflow: "hidden",
    textAlign: "left",
    border: "1px solid #FEE2E2",
    boxShadow: "0 6px 20px rgba(196,30,30,0.06)",
    display: "flex",
    flexDirection: "column",
  },
  courseImageWrapper: {
    position: "relative",
    width: "100%",
    height: isMobile ? "180px" : "200px",
    overflow: "hidden",
  },
  courseImage: {
    width: "100%",
    height: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "#f1e5e5",
  },
  courseBadge: {
    position: "absolute",
    top: "14px",
    right: "14px",
    background: "rgba(196, 30, 30, 0.9)",
    color: "#ffffff",
    fontSize: "11px",
    fontWeight: 700,
    padding: "5px 12px",
    borderRadius: "20px",
    backdropFilter: "blur(4px)",
    letterSpacing: "0.02em",
  },
  courseCardBody: {
    padding: "20px 22px 24px",
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  courseTitle: { fontSize: "18px", color: "#1a1615", marginBottom: "8px", fontWeight: 700 },
  courseDesc: { fontSize: "13.5px", color: "#6b625a", lineHeight: 1.55, marginBottom: "18px", flex: 1 },
  courseLink: { color: "#C41E1E", fontSize: "14px", textDecoration: "none", fontWeight: 700 },

  blogScrollOuter: { overflow: "hidden", width: "100%", padding: "10px 0 20px" },
  blogTrack: { display: "flex", gap: "24px", width: "max-content" },
  blogCard: {
    flex: "0 0 auto",
    width: isMobile ? "260px" : "310px",
    background: "#ffffff",
    borderRadius: "20px",
    overflow: "hidden",
    border: "1px solid #FEE2E2",
    boxShadow: "0 6px 20px rgba(196,30,30,0.08)",
  },
  blogImageWrapper: {
    position: "relative",
    width: "100%",
    height: isMobile ? "150px" : "180px",
    overflow: "hidden",
  },
  blogImage: {
    width: "100%",
    height: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "#f1e5e5",
  },
  blogCategoryTag: {
    position: "absolute",
    bottom: "12px",
    left: "12px",
    background: "#ffffff",
    color: "#C41E1E",
    fontSize: "11px",
    fontWeight: 700,
    padding: "4px 10px",
    borderRadius: "12px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
  },
  blogCardBody: { padding: "20px" },
  blogText: { fontSize: "14px", color: "#1a1615", margin: "0 0 16px", lineHeight: 1.55, fontWeight: 600, minHeight: "44px" },
  blogReadMore: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: "13px",
    fontWeight: 700,
    color: "#ffffff",
    background: "linear-gradient(135deg, #C41E1E 0%, #8E1616 100%)",
    padding: "8px 18px",
    borderRadius: "20px",
    textDecoration: "none",
    boxShadow: "0 4px 12px rgba(196,30,30,0.2)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },

  study: {
    position: "relative",
    overflow: "hidden",
    minHeight: isMobile ? "320px" : "420px",
    display: "flex",
    alignItems: "center",
  },
  studyDim: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(180deg, rgba(142,22,22,0.65) 0%, rgba(80,19,19,0.88) 100%)",
  },
  studyOverlay: {
    position: "relative",
    zIndex: 1,
    padding: isMobile ? "40px 20px" : "64px 48px",
    textAlign: "center",
    color: "#fff",
    maxWidth: "700px",
    margin: "0 auto",
  },
  studyHeading: { fontSize: isMobile ? "18px" : "22px", marginBottom: "4px" },
  studySubheading: { fontSize: isMobile ? "22px" : "28px", letterSpacing: "0.05em", color: "#FFD166", marginBottom: "16px", fontWeight: 800 },
  studyText: { fontSize: isMobile ? "13.5px" : "15px", lineHeight: 1.7, color: "#FCEBEB" },
});